import React from 'react';
// credit goes to alphardex for original code.
function Snow() {
  return (
    <>
      <div className="snow" />
      <div className="snow" />
      <div className="snow" />
      <div className="snow" />
      <div className="snow" />
      <div className="snow" />
      <div className="snow" />
      <div className="snow" />
      <div className="snow" />
      <div className="snow" />
      <div className="snow" />
      <div className="snow" />
      <div className="snow" />
      <div className="snow" />
      <div className="snow" />
      <div className="snow" />
      <div className="snow" />
      <div className="snow" />
      <div className="snow" />
      <div className="snow" />
      <div className="snow" />
      <div className="snow" />
      <div className="snow" />
      <div className="snow" />
      <div className="snow" />
      <div className="snow" />
      <div className="snow" />
      <div className="snow" />
      <div className="snow" />
      <div className="snow" />
      <div className="snow" />
      <div className="snow" />
      <div className="snow" />
      <div className="snow" />
      <div className="snow" />
      <div className="snow" />
      <div className="snow" />
      <div className="snow" />
      <div className="snow" />
      <div className="snow" />
      <div className="snow" />
      <div className="snow" />
      <div className="snow" />
      <div className="snow" />
      <div className="snow" />
      <div className="snow" />
      <div className="snow" />
      <div className="snow" />
      <div className="snow" />
      <div className="snow" />
      <div className="snow" />
      <div className="snow" />
      <div className="snow" />
      <div className="snow" />
      <div className="snow" />
      <div className="snow" />
      <div className="snow" />
      <div className="snow" />
      <div className="snow" />
      <div className="snow" />
      <div className="snow" />
      <div className="snow" />
      <div className="snow" />
      <div className="snow" />
      <div className="snow" />
      <div className="snow" />
      <div className="snow" />
      <div className="snow" />
      <div className="snow" />
      <div className="snow" />
      <div className="snow" />
      <div className="snow" />
      <div className="snow" />
      <div className="snow" />
      <div className="snow" />
      <div className="snow" />
      <div className="snow" />
      <div className="snow" />
      <div className="snow" />
      <div className="snow" />
      <div className="snow" />
      <div className="snow" />
      <div className="snow" />
      <div className="snow" />
      <div className="snow" />
      <div className="snow" />
      <div className="snow" />
      <div className="snow" />
      <div className="snow" />
      <div className="snow" />
      <div className="snow" />
      <div className="snow" />
      <div className="snow" />
      <div className="snow" />
      <div className="snow" />
      <div className="snow" />
    </>
  );
}

export default Snow;
